### ISSUE TITLE
Duplicated asset not appearing when STATAMIC_STACHE_WATCHER=false

### ISSUE THREAD

**Issue by stuartcusackie** [duncanmcclean/duplicator#49]
### Bug Description

Hi, I just noticed that the duplicated asset doesn't show in the control panel when STATAMIC_STACHE_WATCHER=false.

Thanks for the package!

### Steps to reproduce

1. Set STATAMIC_STACHE_WATCHER=false in your environment.
2. Duplicate the asset.

### Environment

Laravel Version: 9.23.0
PHP Version: 8.1.1
Version: 3.3.29 PRO

**Comment by stuartcusackie** [comment]
Hi. There's still a problem when statche watcher is false.

Duplicating seems to replicate the file, however the filesize is 0 bytes and the last modified date is 52 years ago. You have to run the duplicator a second time to get it work correctly.

Apologies for the tiny GIF!
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/20210934/199717919-24bf432f-6db5-4aee-a4a6-86550a41a474.gif)

**Comment by duncanmcclean** [comment]
I'll take another look when I can

**Comment by duncanmcclean** [comment]
I can reproduce locally - think a Statamic update may have broken it. Will try and take a further look this weekend, if I can.

**Comment by stuartcusackie** [comment]
Thank you, no rush on my end. It happens both locally and on staging for me.
