### ISSUE TITLE
Copy items from a collection to other (multi-)site fails

### ISSUE THREAD

**Issue by Sennik** [duncanmcclean/duplicator#51]
### Bug Description

I have created a new site in a multi-site Statamic project (There are already 3 sites running). Everything, including the duplicator plugin is up to date as of today.

When I try to copy items from one of the existing multisites to the freshly created site it fails:
```
Call to a member function page() on null/var/www/openline2022/vendor/statamic/cms/src/Entries/Entry.php#676Error

            return null;
        }

        return $this->structure()->in($this->locale())->page($id);
    }

    public function route()

```

### Steps to reproduce

Use an existing Statamic Multisite environment
Add a site
copy items from one site to another

### Environment

Statamic 3.3.40 Pro
Laravel 8.83.23
PHP 8.1.8
aerni/font-awesome 1.2.0
aryehraber/statamic-color-extractor 1.3.0
aryehraber/statamic-impersonator 2.4.1
doublethreedigital/duplicator 2.3.2
rias/statamic-data-import 1.2.2
webographen/statamic-widget-cache-controller 1.0.1

**Comment by duncanmcclean** [comment]
Is that collection setup in that multisite?

**Comment by Sennik** [comment]
Yes, both sites are part of the same multisite and use the same collection configuration. In total this multisite has 4 sites.

**Comment by Sennik** [comment]
I have it. After adding a site in ststamic/sites.php apperently I also have to add the site to the collections configurations:

![afbeelding](https://user-images.githubusercontent.com/5636394/193198385-efbf43bd-f9e3-4eb1-9475-2e24e1704286.png)

Apparently it's not in the documentation of Statamic?
