### ISSUE TITLE
Duplicate on all sites doesn't work when using statamic/eloquent-driver

### ISSUE THREAD

**Issue by vaites** [duncanmcclean/duplicator#61]
### Description

If entries are stored in database using [statamic/eloquent-driver](https://github.com/statamic/eloquent-driver), when an entry is duplicated to all sites the behaviour is not the expected:

1. The entry contents are copied from original instead from each site
2. If you modify the title of all entry sites, the title on index remains as _Original entry (Duplicated)_
3. Changes made to each site doesn't seems to be reflected on frontent templates

Not sure if this is an issue related to the Eloquent driver or this addon, but if this addon is merged with Statamic core I think this must be at least reviewed.

### Steps to reproduce

1. Setup Statamic to use [statamic/eloquent-driver](https://github.com/statamic/eloquent-driver)
2. Create an entry and translate to 2 or more languages (or sites)
3. Duplicate entry using this addon 
4. Verify the described behaviour

### Environment

**Environment**
Application Name: Statamic
Laravel Version: 9.52.10
PHP Version: 8.2.8
Composer Version: -
Environment: production
Debug Mode: OFF
URL: dinak.com
Maintenance Mode: OFF

**Cache**
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

**Drivers**
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

**Statamic**
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: half
Version: 3.4.11 PRO

**Statamic Addons**
statamic/eloquent-driver: 1.2.0

**Comment by duncanmcclean** [comment]
This might be an issue with the Eloquent Driver itself, since it works fine for non-Eloquent sites. 

Maybe open an issue on the Eloquent Driver to see if it's something that can be sorted there. If it does end up being a Duplicator issue, I can re-open this issue.

**Comment by duncanmcclean** [comment]
In fact, you're using a very old version of the Eloquent Driver. Try updating to the latest version and see if the issue still happens - if it does, open an issue on the Eloquent Driver.

**Comment by vaites** [comment]
Thanks @duncanmcclean, will try to dig deeper and come back with more info. If is an issue from Eloquent driver will open an issue here. 

Anyway, the version is stuck because I'm using Statamic 3.4 and the 2.0 version of Eloquent driver only supports Statamic 4.0.
